version: '3.3'
services:
  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_DATABASE: 'user_app'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_ROOT_PASSWORD: root
    ports:
    - '3306:3306'
    expose:
    - '3306'
    volumes:
    - /tmp:/var/lib/mysql

  springbootdocker:
    image: leandrotula/ws-microservice:v2
    ports:
    - "8081:8081"
    restart: always
    depends_on:
    - db
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: root
      MYSQL_DB_HOST: db
      MYSQL_DB_PORT: 3306
